/* SPDX-License-Identifier: GPL-2.0 */
#ifndef __ASM_MACH_LOONGSON64_IRQ_H_
#define __ASM_MACH_LOONGSON64_IRQ_H_

#include <boot_param.h>

#if defined CONFIG_CPU_LOONGSON3

/* cpu core interrupt numbers */
#define MIPS_CPU_IRQ_BASE 56

#define LOONGSON_UART_IRQ   (MIPS_CPU_IRQ_BASE + 2) /* UART */
#define LOONGSON_BRIDGE_IRQ (MIPS_CPU_IRQ_BASE + 3) /* CASCADE */
#define LOONGSON_TIMER_IRQ  (MIPS_CPU_IRQ_BASE + 7) /* CPU Timer */

#define LOONGSON_HT1_CFG_BASE		loongson_sysconf.ht_control_base
#define LOONGSON_HT1_INT_VECTOR_BASE	(LOONGSON_HT1_CFG_BASE + 0x80)
#define LOONGSON_HT1_INT_EN_BASE	(LOONGSON_HT1_CFG_BASE + 0xa0)
#define LOONGSON_HT1_INT_VECTOR(n)	\
		LOONGSON3_REG32(LOONGSON_HT1_INT_VECTOR_BASE, 4 * (n))
#define LOONGSON_HT1_INTN_EN(n)		\
		LOONGSON3_REG32(LOONGSON_HT1_INT_EN_BASE, 4 * (n))

#define LOONGSON_INT_ROUTER_OFFSET	0x1400
#define LOONGSON_INT_ROUTER_INTEN	\
	  LOONGSON3_REG32(LOONGSON3_REG_BASE, LOONGSON_INT_ROUTER_OFFSET + 0x24)
#define LOONGSON_INT_ROUTER_INTENSET	\
	  LOONGSON3_REG32(LOONGSON3_REG_BASE, LOONGSON_INT_ROUTER_OFFSET + 0x28)
#define LOONGSON_INT_ROUTER_INTENCLR	\
	  LOONGSON3_REG32(LOONGSON3_REG_BASE, LOONGSON_INT_ROUTER_OFFSET + 0x2c)
#define LOONGSON_INT_ROUTER_ENTRY(n)	\
	  LOONGSON3_REG8(LOONGSON3_REG_BASE, LOONGSON_INT_ROUTER_OFFSET + n)
#define LOONGSON_INT_ROUTER_LPC		LOONGSON_INT_ROUTER_ENTRY(0x0a)
#define LOONGSON_INT_ROUTER_HT1(n)	LOONGSON_INT_ROUTER_ENTRY(n + 0x18)

#define LOONGSON_INT_COREx_INTy(x, y)	(1<<(x) | 1<<(y+4))	/* route to int y of core x */

#elif defined CONFIG_CPU_LOONGSON2K
#define MIPS_CPU_IRQ_BASE 0
#define NR_IRQS 192

enum LS2K_ICU {
	LS2K_IRQ_BASE = 8,

	/* 8 */
	UART_I0 = LS2K_IRQ_BASE,
	UART_I1,
	UART_I2,
	E1_I,
	HDA_I,
	I2S_I,
	AC97_I,
	THEN_I,

	/* 16 */
	TOY_TICK_I,
	RTC_TICK_I,
	RESERVED_I0,
	RESERVED_I1,
	GMAC0_I0,
	GMAC0_I1,
	GMAC1_I0,
	GMAC1_I1,

	/* 24 */
	CAN0_I,
	CAN1_I,
	BOOT_I,
	SATA_I,
	NAND_I,
	HPET_I,
	I2C0_I,
	I2C1_I,

	/* 32 */
	PWM0_I,
	PWM1_I,
	PWM2_I,
	PWM3_I,
	DC_I,
	GPU_I,
	RESERVED_I3,
	SDIO_I,

	/* 40 */
	PCI0_I0,
	PCI0_I1,
	PCI0_I2,
	PCI0_I3,
	PCI1_I0,
	PCI1_I1,
	PCI1_I2,
	PCI1_I3,

	/* 48 */
	TOY_I0,
	TOY_I1,
	TOY_I2,
	TOY_I3,
	DMA_I0,
	DMA_I1,
	DMA_I2,
	DMA_I3,

	/* 56 */
	DMA_I4,
	OTG_I,
	EHCI_I,
	OHCI_I,
	RTC_I0,
	RTC_I1,
	RTC_I2,
	RSA_I,

	/* 64 */
	AES_I,
	DES_I,
	GPIO_INT_LO_I,
	GPIO_INT_HI_I,
	GPIO_INT0,
	GPIO_INT1,
	GPIO_INT2,
	GPIO_INT3,

	LS64_MSI_IRQ_BASE = 128,
	LS64_IRQ_LAST = NR_IRQS - 1,
};
#endif

extern void fixup_irqs(void);
extern void loongson3_ipi_interrupt(struct pt_regs *regs);

#include_next <irq.h>
#endif /* __ASM_MACH_LOONGSON64_IRQ_H_ */
